# Generated by Django 4.1.3 on 2023-04-10 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won_team_id', models.PositiveSmallIntegerField(default=0, verbose_name='кто выйграл')),
            ],
            options={
                'verbose_name': 'результат',
                'verbose_name_plural': 'результаты',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='название')),
                ('capacity', models.IntegerField(verbose_name='вместимость')),
                ('city', models.CharField(max_length=25, verbose_name='город')),
            ],
            options={
                'verbose_name': 'стадион',
                'verbose_name_plural': 'стадионы',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='название')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.stadium', verbose_name='стадион')),
            ],
            options={
                'verbose_name': 'команда',
                'verbose_name_plural': 'команды',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='имя')),
                ('surname', models.CharField(max_length=25, verbose_name='фамилия')),
                ('power', models.PositiveSmallIntegerField(verbose_name='сила')),
                ('age', models.PositiveSmallIntegerField(verbose_name='возраст')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Свободный агент'), (1, 'Состоит в команде'), (2, 'Завершил карьеру')], default=0, verbose_name='статус')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='players', to='main.team', verbose_name='команда')),
            ],
            options={
                'verbose_name': 'игрок',
                'verbose_name_plural': 'игроки',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Состоится'), (1, 'В процессе'), (2, 'Состоялось')], default=0, verbose_name='статус')),
                ('result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.result', verbose_name='результат')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='team_1', to='main.team', verbose_name='команда 1')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='team_2', to='main.team', verbose_name='команда 2')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'события',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='сумма')),
                ('chosen_team_id', models.PositiveSmallIntegerField(verbose_name='выбранная команда')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.event', verbose_name='событие')),
            ],
            options={
                'verbose_name': 'ставка',
                'verbose_name_plural': 'ставки',
                'ordering': ('-id',),
            },
        ),
    ]
