# Generated by Django 4.1.3 on 2022-12-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='capacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='место расположения'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='город'),
        ),
    ]
