# Generated by Django 4.1.3 on 2023-01-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_player_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
    ]
