# Generated by Django 4.1.5 on 2023-02-03 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_player_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stadium',
            options={'ordering': ('title',), 'verbose_name': 'стадион', 'verbose_name_plural': 'стадионы'},
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='player',
            name='power',
            field=models.IntegerField(verbose_name='сила'),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Свободный агент'), (1, 'Состоит в команде')], default=0, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='capacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='место расположения'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='title',
            field=models.CharField(max_length=40, verbose_name='название стадиона'),
        ),
        migrations.AlterField(
            model_name='team',
            name='stadium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.stadium', verbose_name='стадион команды'),
        ),
    ]
