# Generated by Django 4.1.3 on 2023-01-04 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.IntegerField(choices=[(1, 'Свободный агент'), (2, 'Играет в команде')], default=1, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='players', to='main.team', verbose_name='команда'),
        ),
    ]
