# Generated by Django 4.1.3 on 2023-01-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_player_status_alter_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Свободный агент'), (1, 'Состоит в команде')], default=0, verbose_name='статус'),
        ),
    ]
